# Site
repository: benjamin-antupit/site
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Benjamin Antupit
title: Stage Automation Technician & Robotics Engineer
email: benjamin@antupit.com
website: benjamin.antupit.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: username
github_username:  benjamin-antupit
# stackoverflow_username: "username"
# dribbble_username: username
# facebook_username: username
# flickr_username: username
# instagram_username: username
linkedin_username: benjamin-antupit
# xing_username: username
# pinterest_username: username
# youtube_username: username
# googleplus_username: +username
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, I'm Benjamin and I'm studying <mark>Robotics Engineering</mark> and <mark>Technical Theatre</mark> at WPI. In my spare time, I am the Technical Director of [WPI Lens and Lights](https://lnl.wpi.edu), a student-run live event production group which produces over 200 events per year. 
  
  I really enjoy exploring the intersection between live entertainment, project management, and engineering which is what led me to Stage Automation and Robotics Engineering. I love exploring lighting design and technical direction in my spare time because I enjoy the creative outlet, collaboration, and bringing joy to audiences.

### Content options: https://github.com/sproogen/modern-resume-theme#content
content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Worcester Polytechnic Institute (WPI)
        sub_title: Combined Bachelor & Master of Science in Robotics Engineering with a Minor in Technical Theatre
        link: www.wpi.edu
        caption: 2021-2025
        #description: | # this will include new lines to allow paragraphs
        #  During my time at WPI, I ...
#
        #  I spent a lot of my free time ...

      - layout: top-middle
        title: Crystal Springs Uplands School
        sub_title: Middle and High School
        link: www.csus.org
        caption: 2014-2021
        #description: | # this will include new lines to allow paragraphs
         # During my time at Crystal, I ...
#
 #         I spent a lot of my free time ...
  - title: Skills # Title for the section
# Live Entertainment Production Tools: TAIT Navigator, PRG Stage Command, Vectorworks, ETC EOS
# Programming Languages: Python (specialized in ROS), MATLAB, Java, C++, TypeScript, and LaTeX
# Design Applications: PTC Creo, Solidworks, Onshape, Adobe Suite, and Affinity Designer
# Industry-specific Networking: Dante Level 3 Certified (2nd Edition), EtherCAT, ArtNet/sACN/ETCNet
# Production Equipment: Chain Hoist Repair, Stage Lifts, Revolves, Moving Lights, Scissor/Boom Lifts

    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Live Entertainment Production Tools
        description: | # this will include new lines to allow paragraphs
          TAIT Navigator, PRG Stage Command, Vectorworks, ETC EOS
      - layout: left
        title: Software Design & Implementation
        description: | # this will include new lines to allow paragraphs
          Python (specialized in ROS), MATLAB, Java, C++, TypeScript, and LaTeX
      - layout: left
        title: Design Applications
        description: | # this will include new lines to allow paragraphs
          PTC Creo, Solidworks, Onshape, Adobe Suite, and Affinity Designer
      - layout: left
        title: Industry-specific Networking
        description: | # this will include new lines to allow paragraphs
          Dante Level 3 Certified (2nd Edition), EtherCAT, Ethernet/IP, and ArtNet/sACN/ETCNet
      - layout: left
        title: Production & Stage Automation Equipment
        description: | # this will include new lines to allow paragraphs
          Chain Hoist (Operation & Repair), Stage Lifts, Revolves, Moving Lights, and Scissor/Boom Lifts

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Scenic Control Systems Intern
        link: https://www.prg.com/en/services/scenic-and-automation
        # link_text: boringcompany.com
        sub_title: PRG Scenic Technologies (New Windsor, NY)
        caption: Summer 2024
        description: | # this will include new lines to allow paragraphs
          • Commissioned new scenic automation systems for NYC & touring Broadway productions

          • Learned to operate and provide field support for scenic automation and performer flying systems

          • Collaboratively designed, specified, fabricated, and supported electronic & mechanical elements
      - layout: left
        title: Control Integration and Field Engineering Intern
        link: https://www.taittowers.com/
        # link_text: boringcompany.com
        sub_title: TAIT Towers (Lititz, PA)
        caption: Summer 2023
        description: | # this will include new lines to allow paragraphs
          • Completed commissioning for stage automation systems used in international concert touring, theater, opera, theme parks, cruise ships, and unique live entertainment applications

          • Worked on 10+ projects in 10 weeks using Beckoff/Siemens PLCs and QNX Linux
          
          • Learned to program automation show control systems with TAIT Navigator 102 certification
      - layout: left
        title: Teaching Assistant
        link: https://www.wpi.edu/academics/study/drama/theatre-minor
        # link_text: boringcompany.com
        sub_title: TH340X - Lighting Design at WPI
        caption: January 2023 - March 2023 (C23)
        description: | # this will include new lines to allow paragraphs
          • Responsible for small-group activities in the Lighting Lab using an ETC ION and ETC LED fixtures

          • Collaborated with professor on course planning and prepared lab space for students 
      - layout: left
        title: Collaborator & Camp Counselor
        link: ProjectEmber.org
        # link_text: boringcompany.com
        sub_title: Project Ember
        caption: Summer 2017 - Summer 2022
        # quote: >
        #   Each week, campers design and build never-before-seen art and engineering projects with power tools, and learn to create something bigger together.
        description: | # this will include new lines to allow paragraphs
          • Collaborated with campers to build large-scale projects with power tools (rising 2nd-8th graders)
          
          • Facilitated imaginative design sessions, interactive tool trainings, large-group brainstorms, and team-building games to create a welcoming learning community
          
          • Advised fellow staff on project planning, feasibility, and designing with safety
      - layout: left
        title: Software Specialist
        link: LiminalET.com
        # link_text: boringcompany.com
        sub_title: AuroBor, LLC (Formerly Liminal Engineering Technologies)
        caption: April 2021 - November 2021
        # quote: >
        #   Each week, campers design and build never-before-seen art and engineering projects with power tools, and learn to create something bigger together.
        description: | # this will include new lines to allow paragraphs
          • Designed, hosted, and presented workshops and open trainings with customers via Zoom

          • Consulted and implemented custom software solutions for key clients

          • Developed new features for controller application within Bitfocus Companion

  - title: Selected Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Disc Golf Inventory System
        sub_title: > 
          WPI + Maple Hill Disc Golf
        caption: Fall 2023 - Spring 2024
        link: https://digital.wpi.edu/concern/student_works/3r0750063
        link_text: Project Report & Poster
        #additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          • Designed, developed, and integrated disc analysis machine with capacity for 300+ discs per hour
          
          • Wore many hats: managed team of 7, developed system integrations, and liaised with client
      - layout: top-middle
        title: 3-DoF Pick-and-place Robotic Manipulator
        sub_title: > 
          RBE3001: Unified Robotics III - Manipulation
        caption: January 2023 - March 2023
        link: https://www.youtube.com/watch?v=wEN4000z8K4
        link_text: Project Summary Video
        #additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          • Developed trajectory-following algorithm and model in Matlab using forward/inverse kinematics
          
          • Collaborated with a team to design and implement a ball sorting routine using computer vision
      - layout: top-middle
        title: > 
          "Escape Room" Robots
        sub_title: > 
          RBE2002: Unified Robotics II - Sensing and Communication
        caption: October 2022 - December 2022
        #link: github.com/sproogen
        # link_text: Project Website
        #additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          • Implemented odometry, kinematics, and gyro/accelerometer fusion on a mobile robot platform 

          • Worked with a team to integrate three robots using MQTT and complete a maze escape challenge
      - layout: top-middle
        title: > 
          Practicum in Theater Lighting Design
        sub_title: > 
          New Voices 39 - A Festival of New Plays
        caption: Febuary 2022 - May 2022
        #link: github.com/sproogen
        # link_text: Project Website
        #additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          • Developed design ideas in collaboration with directors and co-lighting designer

          • Created visually distinct worlds for each show to evoke emotions through light 

          • Communicated results in a report with lighting plots, fixture schedules, and narrative journal using Lightwright, Vectorworks and LaTeX
      - layout: top-middle
        title: > 
          "Solar Panel Installation" Robot
        sub_title: > 
          RBE2001: Unified Robotics I - Mechanisms and Linkages
        caption: August 2022 - October 2022
        #link: github.com/sproogen
        # link_text: Project Website
        #additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          • Learned to synthesize, model, and iterate on linkage designs for manipulation of various objects
          
          • Collaborated with a team of peers to develop strategy, software, and manipulator to place solar panel models on small roofs using sensor-driven feedback loops 

  
  - title: Leadership & Activities # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Technical Director
        link: lnl.wpi.edu
        # link_text: boringcompany.com
        sub_title: WPI Lens and Lights
        caption: |
          Febuary 2024 - Present
        description: | # this will include new lines to allow paragraphs
          • Maintained and coordinated repairs for lighting, audio, and rigging equipment
          
          • Lead trainings and workshops for new and experienced members in rigging, lighting, audio, & more
          
          • Coordinate sub-rentals of event production and rigging equipment from regional & national vendors

      - layout: left
        title: President
        link: lnl.wpi.edu
        # link_text: boringcompany.com
        sub_title: WPI Lens and Lights
        caption: |
          Febuary 2023 - Febuary 2024
        description: | # this will include new lines to allow paragraphs
          • Plan and coordinate lighting and sound services, rental equipment, and student crew for 270+ events per year serving the WPI campus and surrounding communities
          
          • Mentor, train and support 40+ crew members in event planning and technical execution

      - layout: left
        title: Vice President
        link: lnl.wpi.edu
        # link_text: boringcompany.com
        sub_title: WPI Lens and Lights
        caption: |
          Febuary 2022 - Febuary 2023
        description: | # this will include new lines to allow paragraphs
          • Collaborate and partner with clients, service providers, and university departments

          • Organize club activities, advance visits to local venues, and explore new opportunities for members
          
          • Short- and long-term production planning, scheduling, logistics, and equipment allocation
          
          • Coordinate rentals of our equipment to local companies and sub-rentals from regional vendors


      - layout: left
        title: Theatre Production Leader & Crew Member
        link: vox.wpi.edu
        # link_text: boringcompany.com
        sub_title: VOX Musical Theatre and Masque Theatre
        caption: August 2021 - Present
        description: | # this will include new lines to allow paragraphs
          • Technical Director, Lighting Designer, Head Electrician, or Rental Coordinator for 16+ musicals and plays

      - layout: left
        title: Production Manager
        #link: 
        # link_text: boringcompany.com
        sub_title: Various Events in Central Massachusetts
        caption: January 2023 - Febuary 2024
        description: | # this will include new lines to allow paragraphs
          • Focused on events ranging from concerts to fashion shows to nonprofit benefits
          
          • Collaborated with clients and crew to develop vision and budget for video, lighting and sound design

  - title: Awards & Honors # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Class of 1879 Prize
        sub_title: Outstanding Projects in the Humanities
        caption: Febuary 2023
        description: | # this will include new lines to allow paragraphs
           The Class of 1879 Prize is awarded by the Humanities & Arts department yearly for excellent work in the culminating project for the Humanities & Arts Requirement. These projects must demonstrate exceptional creativity and skill in conceiving, developing, and expressing a theme within any discipline in the humanities and arts.  
        link: https://benjamin.antupit.com/assets/Benjamin_Antupit-TH3910_HUA_Practicum.pdf
        link_text: View Project Portfolio
      - layout: left
        title: Social Innovation Challenge
        sub_title: 1st Place, Team Adaptly
        caption: Febuary 2022
        description: | # this will include new lines to allow paragraphs
           An annual competition hosted by the WPI Entrepreneurship Center, the Social Innovation Challenge is a 24-hour event where teams of students from across the university come together to develop a solution to a social problem. Adaptly was awarded 1st place for our proposal for a professional connections network.
      - layout: left
        title: Founders Award
        sub_title: Crystal Springs Uplands School
        caption: June 2021
        description: | # this will include new lines to allow paragraphs
           Colloquially known as the "Unsung Hero's Award," this award is presented by the Head of School to the senior who contributes to the spirit of the school by best exemplifying these qualities we value: integrity, generosity of spirit, enthusiasm, resilience, consideration and reliability.
      - layout: left
        title: Project Invent
        sub_title: Judge's Award, Team Ruby
        caption: May 2020
        description: | # this will include new lines to allow paragraphs
          As a team, we learned about the challenges of a mobility-challenged senior and specifically, their difficulty in tying their shoes. We designed a shoe tying device that would allow the user to tap their ankles and their shoe would secure itself without the need for hand mobility. Our device was awarded the Judge's Award for its innovative design and potential to make a positive impact on the lives of mobility-challenged adults.

  #- title: A Little More About Me
  #  layout: text
  #  content: | # this will include new lines to allow paragraphs
  #    Alongside my interests in ..., some of my other interests and hobbies are:
  #    - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua
  #    - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua
  #    - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua

     # Look at this cool image  
     # ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true # false
references_title: References avaliable upon request (contact `benjamin` at `antupit` dot `com`)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
